# Generated by Django 4.0.4 on 2022-07-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_page',
            field=models.BooleanField(default=True),
        ),
    ]
