# Generated by Django 4.0.4 on 2022-08-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default='empty', max_length=64),
            preserve_default=False,
        ),
    ]
