# Generated by Django 4.0.4 on 2022-08-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
